added TA Assignment test
bptome/TAScheduler pull request #20
Opened 2021-12-19 21:35 UTC by azewudie

2021-12-19 21:46 UTC, bptome requested changes

2021-12-19 21:46 UTC, bptome commented on TAInformation/views.py
> +         Extract data from form
should "extract data from form" be a comment here?

2021-12-19 22:00 UTC, OmarHHammad reviewed
Overall, LGTM! Some minor tweaks but nice job

2021-12-19 22:00 UTC, OmarHHammad commented on TAInformation/views.py
> +     this is a dummy method. will eventually use user_id and return a User() class of the user that matches the user_id
this should be a comment

2021-12-19 22:00 UTC, OmarHHammad commented on virtualenv
> +Collecting virtualenv
this file can be deleted

2021-12-20 01:28 UTC, bptome approved these changes

2021-12-20 13:59 UTC, vaishnavi-manikonda approved these changes
LGTM

2021-12-20 15:09 UTC, merged