Log in unit tests
bptome/TAScheduler pull request #4
Opened 2021-12-03 17:58 UTC by vaishnavi-manikonda

2021-12-03 20:11 UTC, TerryvilleDev requested changes
You'll need to add the line I pointed out in the other comment of my review.  Also, It'll be a good a idea to talk what we expected for validation when we both have an opportunity.

2021-12-03 20:11 UTC, TerryvilleDev commented on LearnDjango/tests/TestLogIn.py
> +
You'll need to add __from TAInformation.Models.account_type import AccountType__ to use the AccountType enum values.

2021-12-05 17:40 UTC, bptome commented
I'll approve it so we can continue working, but (obviously) you will need to merge in master to your branch to make changes that will work.

2021-12-05 17:41 UTC, bptome approved these changes

2021-12-06 20:38 UTC, TerryvilleDev approved these changes

2021-12-07 13:51 UTC, merged